/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add proton

#NOTE: this is set to 1 for minimum information at each step.
# Setting it to 2 will print all information about secondary particles
#0,-1 will set it to silent configuration
/tracking/verbose 

/vis/viewer/set/viewpointVector -1 0 0 
/vis/viewer/zoom 21
#/vis/ogl/set/exportFormat jpg

/gun/particle e-
#/gun/particle proton

/gun/energy 4 MeV
/run/beamOn 100
/vis/ogl/export Ogl_output/500particles_100MeV_proton


