# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
/run/printProgress
#
/control/verbose 0
/run/verbose 0
#/event/verbose 1
/tracking/verbose 2 
/hits/verbose 1
#/tracking/storeTrajectory 3
# 
# gamma 6 MeV to the direction (0.,0.,1.)
#
#/gun/particle gamma
#/gun/energy 6 MeV
#
#/run/beamOn 5
# 
# proton 210 MeV to the direction (0.,0.,1.)
#
#/gun/particle proton
#/gun/energy 210 MeV
#/tracking/verbose 2
#
#/run/beamOn 1

#/gun/particle proton
#/gun/energy 10 keV
#
#/run/beamOn 1

#/hits/list


/gun/particle e-
/gun/energy 15 keV

/run/beamOn 1 

/hits/list
